/*
===============================================================================
Table       : notifications
Description :
Stores notification records generated by the system.
===============================================================================
*/

USE product_adda_db;

DROP TABLE IF EXISTS notifications;

-- ============================================================================
-- Create Table
-- ============================================================================

CREATE TABLE notifications
(
    pk_notification_id BINARY(16) NOT NULL,

    fk_user_id BINARY(16) NOT NULL,

    fk_type_id BINARY(16) NOT NULL,

    fk_channel_id BINARY(16) NOT NULL,

    title VARCHAR(255) NOT NULL,

    message TEXT NOT NULL,

    is_read BOOLEAN NOT NULL DEFAULT FALSE,

    sent_at_utc TIMESTAMP NULL,

    created_at_utc TIMESTAMP NOT NULL
        DEFAULT (UTC_TIMESTAMP()),

    updated_at_utc TIMESTAMP NOT NULL
        DEFAULT (UTC_TIMESTAMP())
        ON UPDATE CURRENT_TIMESTAMP,

    is_active BOOLEAN NOT NULL DEFAULT TRUE,


    CONSTRAINT pk_notifications_notification_id
        PRIMARY KEY (pk_notification_id),


    CONSTRAINT fk_notifications_user_id
        FOREIGN KEY (fk_user_id)
        REFERENCES users(pk_user_id)
        ON DELETE RESTRICT,


    CONSTRAINT fk_notifications_type_id
        FOREIGN KEY (fk_type_id)
        REFERENCES notification_types(pk_notification_type_id)
        ON DELETE RESTRICT,


    CONSTRAINT fk_notifications_channel_id
        FOREIGN KEY (fk_channel_id)
        REFERENCES notification_channels(pk_channel_id)
        ON DELETE RESTRICT
);

-- ============================================================================
-- Indexes
-- ============================================================================

CREATE INDEX idx_notifications_user_id
ON notifications(fk_user_id);


CREATE INDEX idx_notifications_type_id
ON notifications(fk_type_id);


CREATE INDEX idx_notifications_channel_id
ON notifications(fk_channel_id);


CREATE INDEX idx_notifications_is_read
ON notifications(is_read);


CREATE INDEX idx_notifications_sent_at
ON notifications(sent_at_utc);


CREATE INDEX idx_notifications_is_active
ON notifications(is_active);

-- ============================================================================
-- Verification
-- ============================================================================

DESCRIBE notifications;

SHOW CREATE TABLE notifications;
