spring.application.name=productadda

spring.datasource.url=jdbc:mysql://localhost:3306/product_adda_db
spring.datasource.username=productaddaAppServiceAcc
spring.datasource.password=codeaxisFuison1

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
