USE product_adda_db;

/*
===============================================================================
SEED DATA FOR AUTHENTICATION & SECURITY TABLES
===============================================================================

NOTE:
Dummy development data only.

Production:
Tokens should be generated by application services.

===============================================================================
*/

/*==============================================================
000. TRUNCATE
==============================================================*/

SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE `password_reset_tokens`;
TRUNCATE TABLE `refresh_tokens`;
TRUNCATE TABLE `email_verification_tokens`;

SET FOREIGN_KEY_CHECKS = 1;

/*
===============================================================================
030. SEED DATA FOR: email_verification_tokens
===============================================================================
*/
-- INSERT INTO email_verification_tokens (pk_verification_token_id, fk_user_id, verification_token, expires_at_utc, is_used, created_at_utc) VALUES 
-- (UUID_V7(), (SELECT pk_user_id FROM users WHERE email='rahul.verma@gmail.com'), 'verify-demo-token-001', '2025-01-11 09:15:00', FALSE, '2025-01-10 09:15:00');

/*
===============================================================================
031. SEED DATA FOR: refresh_tokens
===============================================================================
*/
-- INSERT INTO refresh_tokens (pk_refresh_token_id, fk_user_id, token_hash, expires_at_utc, created_at_utc) VALUES 
-- (UUID_V7(), (SELECT pk_user_id FROM users WHERE email='rahul.verma@gmail.com'), 'refresh-token-hash-demo-001', '2025-05-31 14:00:00', '2025-05-01 14:00:00');

/*
===============================================================================
032. SEED DATA FOR: password_reset_tokens
===============================================================================
*/
-- INSERT INTO password_reset_tokens (pk_reset_token_id, fk_user_id, token_hash, expires_at_utc, is_used, created_at_utc) VALUES 
-- (UUID_V7(), (SELECT pk_user_id FROM users WHERE email='rahul.verma@gmail.com'), 'password-reset-hash-demo-001', '2025-06-15 11:15:00', FALSE, '2025-06-15 11:00:00');
