package com.productadda.service.notifications;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.productadda.dto.notifications.NotificationContentDto;

import com.productadda.entity.Notification;
import com.productadda.entity.NotificationChannel;
import com.productadda.entity.NotificationType;
import com.productadda.entity.Order;
import com.productadda.entity.Payment;
import com.productadda.entity.RecipientRole;
import com.productadda.entity.DispatchStatus;
import com.productadda.entity.User;

import com.productadda.exception.ApiException;

import com.productadda.repository.DispatchStatusRepository;
import com.productadda.repository.NotificationChannelRepository;
import com.productadda.repository.NotificationRepository;

import com.productadda.util.UuidUtil;

import lombok.RequiredArgsConstructor;

@Service
@RequiredArgsConstructor
public class NotificationCreationService {

    private static final Logger log = LoggerFactory.getLogger(NotificationCreationService.class);

    // Channel scope: only EMAIL and IN_APP get rows created. SMS/PUSH
    // are deferred until provider integration exists.
    private static final List<String> CHANNEL_NAMES = List.of("EMAIL", "IN_APP");

    private final NotificationChannelRepository notificationChannelRepository;
    private final DispatchStatusRepository dispatchStatusRepository;
    private final NotificationRepository notificationRepository;

    private final TemplateContentResolverService templateContentResolverService;

    private final UuidUtil uuidUtil;

    /*
     * ================================================================
     * CREATE NOTIFICATIONS FOR RECIPIENT
     * Description: Central write path for the notification system.
     * Given one recipient (already resolved to a User -- even when they
     * are really a vendor/delivery-partner/admin acting through their
     * base user account) and one business event, creates one
     * `notifications` row per channel (EMAIL, IN_APP), each with
     * dispatch_status = PENDING, ready for QueueProcessorWorker.
     *
     * change: content is now resolved PER CHANNEL, inside this
     * loop, via TemplateContentResolverService -- not built once
     * upstream and reused for every channel -- so EMAIL and IN_APP can
     * genuinely differ once role/channel-specific templates exist.
     * Callers now pass the raw context map instead of a pre-built
     * NotificationContentDto. recipient_role is injected into the
     * context automatically here, so handlers never need to set it
     * themselves.
     *
     * event_id is shared across every row created from a single call to
     * this method (event_id + user + channel is the DB-level dedup key)
     * but is freshly generated by the caller per invocation -- see the
     * idempotency caveat on the Notification entity.
     * ================================================================
     */
    @Transactional
    public void createNotificationsForRecipient(
            User recipientUser,
            RecipientRole recipientRole,
            NotificationType notificationType,
            UUID eventId,
            Order order,
            Payment payment,
            Map<String, Object> context) {

        /*
         * ================================================================
         * 1. VALIDATION SECTION
         * ================================================================
         */

        // ==========================================
        // 1.1 REQUEST VALIDATION
        // ==========================================
        if (recipientUser == null || recipientUser.getPkUserId() == null) {
            throw new ApiException(HttpStatus.INTERNAL_SERVER_ERROR,
                    "recipientUser is required to create notifications");
        }
        if (notificationType == null || eventId == null || context == null) {
            throw new ApiException(HttpStatus.INTERNAL_SERVER_ERROR,
                    "notificationType, eventId and context are required to create notifications");
        }

        // ==========================================
        // 1.2 CONTEXT AUTHENTICATION
        // ==========================================
        // N/A - internal service invoked only by EventListenerService*
        // classes, which are themselves invoked from already-authenticated
        // business flows (order/payment/delivery services).

        // ==========================================
        // 1.3 DATABASE LOOKUP VALIDATION
        // ==========================================
        DispatchStatus pendingStatus = dispatchStatusRepository.findByStatusName("PENDING")
                .orElseThrow(() -> new ApiException(HttpStatus.INTERNAL_SERVER_ERROR,
                        "PENDING dispatch status lookup row not found"));

        /*
         * ================================================================
         * 2. BUSINESS RULES & PROCESSING / WORKFLOW
         * ================================================================
         */
        Map<String, Object> enrichedContext = new HashMap<>(context);
        enrichedContext.put("recipient_role", recipientRole != null ? recipientRole.getRoleName() : null);

        for (String channelName : CHANNEL_NAMES) {

            NotificationChannel channel = notificationChannelRepository.findByChannelName(channelName)
                    .orElseThrow(() -> new ApiException(HttpStatus.INTERNAL_SERVER_ERROR,
                            channelName + " notification channel lookup row not found"));

            NotificationContentDto content = templateContentResolverService.resolveContent(
                    notificationType, channel, recipientRole, enrichedContext);

            Notification notification = Notification.builder()
                    .pkNotificationId(uuidUtil.generateUuidV7())
                    .eventId(eventId)
                    .fkUser(recipientUser)
                    .fkType(notificationType)
                    .fkChannel(channel)
                    .fkOrder(order)
                    .fkPayment(payment)
                    .fkRecipientRole(recipientRole)
                    .fkDispatchStatus(pendingStatus)
                    .retryCount(0)
                    .title(content.getSubject())
                    .message(content.getBody())
                    .isRead(false)
                    .isActive(true)
                    .build();

            /*
             * ================================================================
             * 3. DB SAVING SECTION
             * ================================================================
             */
            try {
                notificationRepository.save(notification);
            } catch (DataIntegrityViolationException ex) {
                // Composite unique key (event_id, fk_user_id, fk_channel_id)
                // tripped -- treat as an already-processed duplicate and
                // move on rather than failing the whole event.
                log.warn("Duplicate notification skipped for eventId={}, userId={}, channel={}",
                        eventId, recipientUser.getPkUserId(), channelName);
            }
        }

        /*
         * ================================================================
         * 4. POST-SAVING DATA SANITIZATION & MASKING
         * Reason: N/A - void method, no response payload.
         * ================================================================
         */

        /*
         * ================================================================
         * 5. RESPONSE MAPPING
         * Reason: N/A - internal service, not directly bound to a REST
         * endpoint.
         * ================================================================
         */
    }
}
